export const url_base = 'https://bk.winby.co/'
// export const url_base = 'https://winbyubs4e.winby.co/'
//export const url_base = 'http://localhost:3001/'
export const ERROR_CATCH = { success: 0, message: 'No ha recibido respuesta del servidor, por favor intente mas tarde.' }

// /** Store */
export const GET_ALL_CATEGORIES_SERVICE_STORE = 'GET_ALL_CATEGORIES_SERVICE_STORE'
export const GET_ONE_CATEGORIES_SERVICE_STORE = 'GET_ONE_CATEGORIES_SERVICE_STORE'
export const GET_ALL_CATEGORIES_PRODUCTS_STORE = 'GET_ALL_CATEGORIES_PRODUCTS_STORE'
export const GET_ONE_CATEGORIES_PRODUCTS_STORE = 'GET_ONE_CATEGORIES_PRODUCTS_STORE'
export const GET_ALL_PRODUCTS_STORE = 'GET_ALL_PRODUCTS_STORE'
export const GET_ALL_SERVICES_STORE = 'GET_ALL_SERVICES_STORE'
export const SEARCH_ALL_BANNERS = 'SEARCH_ALL_BANNERS'
export const GET_ALL_STORE_KITS = 'GET_ALL_STORE_KITS'

/** Aliados Comerciales */
export const GET_ALL_VENDORS = 'GET_ALL_VENDORS'
export const GET_ONE_VENDORS = 'GET_ONE_VENDORS'

/** Categorías y Sub Categorías */
export const GET_ALL_CATEGORIES_SERVICES = 'GET_ALL_CATEGORIES_SERVICES'
export const GET_ALL_SUB_CATEGORIES_SERVICES = 'GET_ALL_SUB_CATEGORIES_SERVICES'
export const GET_ALL_CATEGORIES_PRODUCTS = 'GET_ALL_CATEGORIES_PRODUCTS'
export const GET_ALL_SUB_CATEGORIES_PRODUCTS = 'GET_ALL_SUB_CATEGORIES_PRODUCTS'

/** usuario */
export const LOGIN_USER = 'LOGIN_USER'
export const GET_ONE_ID_USER = 'GET_ONE_ID_USER'
export const REGISTER_USER = 'REGISTER_USER'
export const PROFILE_USER = 'PROFILE_USER'
export const REGISTER_FRANCHISE = 'REGISTER_FRANCHISE'
export const LOGOUT = 'LOGOUT'
// Recuperar contraseña
export const USER_RECOVER_ACCOUNT = 'USER_RECOVER_ACCOUNT'
export const USER_RECOVER_VALIDATE_TOKEN = 'USER_RECOVER_VALIDATE_TOKEN'
export const USER_RECOVER_CHANGE_PASS = 'USER_RECOVER_CHANGE_PASS'

/** facturas */
export const REGISTER_INVOICES = 'REGISTER_INVOICES'
export const CONFIRM_EPAYCO_INVOICES = 'CONFIRM_EPAYCO_INVOICES'
export const GET_ONE_INVOICES = 'GET_ONE_INVOICES'
export const GET_ALL_INVOICES = 'GET_ALL_INVOICES'

/** Productos */
export const GET_ONE_PRODUCTS = 'GET_ONE_PRODUCTS'
export const GET_ONE_SERVICES = 'GET_ONE_SERVICES'
export const GET_ALL_PRODUCTS = 'GET_ALL_PRODUCTS'
export const GET_ALL_SERVICES = 'GET_ALL_SERVICES'
export const GET_ALL_SIMILAR_PRODUCTS = 'GET_ALL_SIMILAR_PRODUCTS'
export const GET_ALL_SIMILAR_SERVICES = 'GET_ALL_SIMILAR_SERVICES'
export const GET_SCHEDULLE_SERVICES = 'GET_SCHEDULLE_SERVICES'
export const ORDER_ITEMS_STORE = 'ORDER_ITEMS_STORE'
export const GET_VIEWS_PRODUCTS = 'GET_VIEWS_PRODUCTS'
export const GET_VIEWS_SERVICES = 'GET_VIEWS_SERVICES'
export const SEARCH_ALL_OFFERS = 'SEARCH_ALL_OFFERS'

/** Notificaciones */
export const NOTIFICATIONS_SEARCH_ALL = 'NOTIFICATIONS_SEARCH_ALL'
export const NOTIFICATIONS_CHANGE_STATE = 'NOTIFICATIONS_CHANGE_STATE'

/** Proveedores */
export const REGISTER_PARTNER = 'REGISTER_PARTNER'
export const REGISTER_PARTNER_DOCUMENTS = 'REGISTER_PARTNER_DOCUMENTS'
export const GET_ONE_LEGAL_PROVIDER = 'GET_ONE_LEGAL_PROVIDER'

/** Wallet */
export const GET_ONE_USER_MONEY = 'GET_ONE_USER_MONEY'
export const GET_ALL_MONEY_REPORT = 'GET_ALL_MONEY_REPORT'
export const WALLET_USER = 'WALLET_USER'
export const GET_ALL_BANK_USER = 'GET_ALL_BANK_USER'
export const DELETE_BANK_USER = 'DELETE_BANK_USER'
export const REGISTER_BANK_USER = 'REGISTER_BANK_USER'
export const REGISTER_IDENTITIES_USER = 'REGISTER_IDENTITIES_USER'

// Retirar dinero
export const WITHDRAWALS_MONEY_USER = 'WITHDRAWALS_MONEY_USER'

/** Utilidades */
export const GET_ALL_TYPE_IDENTITYS = 'GET_ALL_TYPE_IDENTITYS'
export const GET_ONE_TYPE_IDENTITYS = 'GET_ONE_TYPE_IDENTITYS'
export const GET_ALL_TYPE_ADDRESS = 'GET_ALL_TYPE_ADDRESS'
export const GET_ONE_TYPE_ADDRESS = 'GET_ONE_TYPE_ADDRESS'
export const GET_ALL_CATEGORIES = 'GET_ALL_CATEGORIES'
export const GET_ONE_CATEGORIES = 'GET_ONE_CATEGORIES'
export const GET_ALL_COLORS = 'GET_ALL_COLORS'
export const GET_ONE_COLORS = 'GET_ONE_COLORS'
export const GET_ALL_COUNTRIES = 'GET_ALL_COUNTRIES'
export const GET_ONE_COUNTRIES = 'GET_ONE_COUNTRIES'
export const GET_ALL_DEPARTMENTS = 'GET_ALL_DEPARTMENTS'
export const GET_ONE_DEPARTMENTS = 'GET_ONE_DEPARTMENTS'
export const GET_ALL_MUNICIPALITY = 'GET_ALL_MUNICIPALITY'
export const GET_ONE_MUNICIPALITY = 'GET_ONE_MUNICIPALITY'
export const GET_ALL_TYPE_BANKS = 'GET_ALL_TYPE_BANKS'
export const GET_ONE_TYPE_BANKS = 'GET_ONE_TYPE_BANKS'
export const GET_ALL_ACCOUNTS_TYPE = 'GET_ALL_ACCOUNTS_TYPE'
export const GET_ONE_ACCOUNTS_TYPE = 'GET_ONE_ACCOUNTS_TYPE'

/** variables del buscador */
export const GET_ALL_SEARCH_CATEGORIES = 'GET_ALL_SEARCH_CATEGORIES'
export const GET_ALL_SEARCH_PRODUCTS = 'GET_ALL_SEARCH_PRODUCTS'

/** Store */
export const POST_FORMLANDING = 'POST_FORMLANDING'
// Criptomoneda
export const GET_ALL_TYPE_CRYPTOCURRENCIES = 'GET_ALL_TYPE_CRYPTOCURRENCIES'

// Landing form contact
export const POST_LANDING_FORM_CONTACT = 'POST_LANDING_FORM_CONTACT'
export const POST_LANDING_PHONE_CONTACT = 'POST_LANDING_PHONE_CONTACT'

//Guardar ubicación
export const POST_LOCATION_USER = 'POST_LOCATION_USER'

//Ayudas PQR
export const REGISTER_PQR = 'REGISTER_PQR'
export const GET_ALL_PQR = 'GET_ALL_PQR'
export const GET_ALL_TYPES_PQR = 'GET_ALL_TYPES_PQR'
export const UPDATE_PQR = 'UPDATE_PQR'